### ISSUE TITLE
High input lag compared to UT99 and UT3

### ISSUE THREAD

**Issue by Calypto** [OldUnreal/UT2004Patches#57]
Using each engine's respective Stalwart as the map with an unlit black/white sheet placed in the same spot (340 FPS VRR, 6000 samples each), here is the "motion to photon" latency (measured using an Arduino):

`3.14ms` UT99 XOpenGL ("NoBuffering" is repeatably .3ms slower in case someone cares)
`3.07ms` UT99 D3D9 DirectInput
`3.02ms` UT99 D3D9
`5.76ms` UT2004 OpenGL
`5.74ms` UT2004 D3D9
`3.26ms` UT3

I'm guessing there's a frame being buffered somewhere that isn't ReduceMouseLag (it's even worse with it enabled).

**Comment by stijn-volckaert** [comment]
This happened because the game window was not set to topmost. We fixed it a while back

**Comment by Calypto** [comment]
Which version fixes this? Because in P9 I am getting the same results as 3369.

**Comment by Calypto** [comment]
Still the same high latency in 3374P17. 3ms in UT99 vs 5ms in UT2004.

**Comment by ukpiglet** [comment]
That's because it's still in development and not announced in the release notes....

**Comment by MariosK145** [comment]
@Calypto 
I do not have a setup to test this on Linux, would you be able to install linux and repeat the tests there? 
For my system I consistently have 4-6ms lower input lag than Windows 10, but I am testing in a way that has huge error margins
 
Also, are you using any kind of variable refresh rate monitor?

**Comment by Calypto** [comment]
I had a working troonix install but the distribution I use still doesn't have working Blackwell support (lol). Maybe I'll install something else, but I'm not too keen on it.

Yes it is VRR but that doesn't affect the outcome.

**Comment by marcoburato** [comment]
@Calypto Could you clarify what you measured and how exactly?

On macOS, I've measured a delay between 48ms-68ms between mouse button click and weapon fire on screen. I used an oscilloscope with the mouse switch wired to one channel and a photodiode pointed at the screen on the other channel (to detect the bright instagib blast standing right in front of a wall).

At my 240 fps, a frame takes about 4ms to render. My mouse sampling rate is 250 Hz, so that's another 4ms. The monitor refresh rate is 60 Hz, which might add up to another 16.7ms... I don't have VSync enabled, but I'm not sure if the monitor would buffer the whole frame before displaying it or not. Ignoring the input processing time, I would expect about 1-25ms in total (best case to worst case). So, I feel like there's definitely something wrong.

**Comment by MariosK145** [comment]
> [@Calypto](https://github.com/Calypto) Could you clarify what you measured and how exactly?
> 
> On macOS, I've measured a delay between 48ms-68ms between mouse button click and weapon fire on screen. I used an oscilloscope with the mouse switch wired to one channel and a photodiode pointed at the screen on the other channel (to detect the bright instagib blast standing right in front of a wall).
> 
> At my 240 fps, a frame takes about 4ms to render. My mouse sampling rate is 250 Hz, so that's another 4ms. The monitor refresh rate is 60 Hz, which might add up to another 16.7ms... I don't have VSync enabled, but I'm not sure if the monitor would buffer the whole frame before displaying it or not. Ignoring the input processing time, I would expect about 1-25ms in total (best case to worst case). So, I feel like there's definitely something wrong.

Make sure you test instant action and use shock rifle primary fire, that's the only way to elliminate network processing or weapon fire animation delays

It could also be VSync causing 2x delay with frames buffering

**Comment by rxut** [comment]
> [@Calypto](https://github.com/Calypto) Could you clarify what you measured and how exactly?
> 
> On macOS, I've measured a delay between 48ms-68ms between mouse button click and weapon fire on screen. I used an oscilloscope with the mouse switch wired to one channel and a photodiode pointed at the screen on the other channel (to detect the bright instagib blast standing right in front of a wall).
> 
> At my 240 fps, a frame takes about 4ms to render. My mouse sampling rate is 250 Hz, so that's another 4ms. The monitor refresh rate is 60 Hz, which might add up to another 16.7ms... I don't have VSync enabled, but I'm not sure if the monitor would buffer the whole frame before displaying it or not. Ignoring the input processing time, I would expect about 1-25ms in total (best case to worst case). So, I feel like there's definitely something wrong.

Try using the weapon muzzle to measure. I've tested UT99 Input Lag using NVIDIA Reflex Latency Analyzer via a G-SYNC Monitor that has the hardware.

You can see the test conditions and results here for UT99: [UT99 Input Lag Test](https://docs.google.com/spreadsheets/d/1Ym3JsIyil70PpSqEyGgp7DC6FNH7XZnf2BZNJqaVmsE/edit?gid=1867707120#gid=1867707120)

**Comment by ukpiglet** [comment]
@Calypto What's your discord id? We have a new version it would be interesting to see results from you setup on.

**Comment by marcoburato** [comment]
> Make sure you test instant action and use shock rifle primary fire, that's the only way to elliminate network processing or weapon fire animation delays
> 
> It could also be VSync causing 2x delay with frames buffering

Yes, I tested in Instant Action so there should be not network effect.

I double-checked and I can't see an option in the game settings to enable VSync. In UT2004.ini, I can see `UseVSync=False` under `[OpenGLDrv.OpenGLRenderDevice]` (which is the selected renderer).


> Try using the weapon muzzle to measure. I've tested UT99 Input Lag using NVIDIA Reflex Latency Analyzer via a G-SYNC Monitor that has the hardware.
> 
> You can see the test conditions and results here for UT99: [UT99 Input Lag Test](https://docs.google.com/spreadsheets/d/1Ym3JsIyil70PpSqEyGgp7DC6FNH7XZnf2BZNJqaVmsE/edit?gid=1867707120#gid=1867707120)

My makeshift "sensor" can't target a very small screen area. I placed it near the centre of the screen and stood in front of a wall so that most of the screen would lit up when shooting. It's instagib, so I believe it should be instant.

Your analysis is very interesting. From what I've found about _NVIDIA Reflex Latency Analyzer_, I believe it can't measure the time from physical mouse click to event delivery on USB, but it's a good measurement overall. It confirms my latency is terrible.

**Comment by Calypto** [comment]
@ukpiglet 
It looks like in `UGameEngine::Tick`, input polling happens at the same time as rendering and happens at the very end of the loop (the last `Client->Tick();`). `UViewport::ReadInput` should happen before `GLevel->Tick()`.

**Comment by stijn-volckaert** [comment]
This will be fixed in the release candidate
